agent:
  batch_size: 128
  buffer_size: 100000
  exploration_final_eps: 0.07
  exploration_fraction: 0.4
  exploration_initial_eps: 1.0
  gamma: 0.999
  gradient_steps: 8
  learning_rate: 0.0001
  learning_starts: 20000
  max_grad_norm: 10.0
  net_kwargs:
    net_arch:
    - 64
    - 64
  probabilistic:
  - false
  - false
  stats_window_size: 100
  target_update_interval: 600
  tau: 1.0
  train_freq: 16
agent_class: MultiAgent
environment:
  cardinal_prey: true
  dist_mult: 1
  frame_delay: 5
  icon_scale: 0.05
  include_loc_obs: true
  include_ray_obs: true
  include_ray_type_obs: true
  intermediate_dist_reward: false
  intermediate_ray_reward: negative
  manual_control: false
  min_distance: 0.0
  num_predators: 1
  num_preys: 0
  num_rays: 16
  obs_image: false
  obstacle_file: assets/obstacles/obstacle-letterL.csv
  predator_move_speed: 2
  predator_spawn_area:
  - - 0
    - 0.7
  - - 0.5
    - 1
  prey_move_speed: 2
  prey_spawn_area:
  - - 0.4
    - 0.4
  - - 0.6
    - 0.6
  random_action: false
  random_predator: true
  random_prey: true
  resolution: 800
  reward_mult: 10.0
  show_rays: false
  trunc_limit: 300
environment_class: DroneCatch-v1
learn:
  log_interval: 10
  total_timesteps: 200000
