agent:
  batch_size: 128
  buffer_size: 100000
  exploration_final_eps: 0.07
  exploration_fraction: 0.2
  exploration_initial_eps: 1.0
  gamma: 0.99
  gradient_steps: 8
  learning_rate: 0.0001
  learning_starts: 1000
  max_grad_norm: 10.0
  net_kwargs:
    net_arch:
    - 64
    - 64
  probabilistic:
  - true
  - true
  stats_window_size: 100
  target_update_interval: 600
  tau: 1.0
  train_freq: 16
agent_class: MultiAgent
environment:
  cardinal_prey: true
  dist_mult: 0.1
  frame_delay: 5
  icon_scale: 0.05
  manual_control: false
  min_distance: 0.5
  num_predators: 1
  num_preys: 1
  num_rays: 8
  obs_image: false
  predator_move_speed: 2
  prey_move_speed: 2
  random_predator: true
  random_prey: true
  resolution: 800
  reward_mult: 10.0
  show_rays: false
  trunc_limit: 300
environment_class: DroneCatch-v1
learn:
  log_interval: 10
  total_timesteps: 10000
