algorithm: dqn
environment:
  dist_mult: 0.1
  frame_delay: 1
  icon_scale: 0.1
  manual_control: false
  obs_image: false
  predator_move_speed: 5
  prey_move_angle: 5
  radius: 0.8
  random_predator: true
  random_prey: true
  render_mode: human
  resolution: 800
  reward_mult: 10.0
  trunc_limit: 300
learn:
  total_timesteps: 200000.0
model:
  _init_setup_model: true
  batch_size: 32
  buffer_size: 100000
  device: auto
  exploration_final_eps: 0.05
  exploration_fraction: 0.3
  exploration_initial_eps: 1.0
  gamma: 0.99
  gradient_steps: 1
  learning_rate: 0.0001
  learning_starts: 50000
  max_grad_norm: 10
  optimize_memory_usage: false
  policy_kwargs: null
  replay_buffer_class: null
  replay_buffer_kwargs: null
  seed: null
  stats_window_size: 100
  target_update_interval: 10000
  tau: 1.0
  tensorboard_log: ./logs
  train_freq: 4
  verbose: 1
